[package]
name = "fcmp_rust"
version = "0.0.0"
edition = "2021"

[lib]
name = "fcmp_rust"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
full-chain-membership-proofs = { path = "../../../external/fcmp-plus-plus/crypto/fcmps" }
ciphersuite = { path = "../../../external/fcmp-plus-plus/crypto/ciphersuite", features = ["helioselene", "ed25519"] }

ec-divisors = { path = "../../../external/fcmp-plus-plus/crypto/divisors", features = ["ed25519"] }
rand_core = { version = "0.6", features = ["getrandom"] }
transcript = { package = "flexible-transcript", path = "../../../external/fcmp-plus-plus/crypto/transcript", features = ["recommended"] }
generalized-bulletproofs = { path = "../../../external/fcmp-plus-plus/crypto/generalized-bulletproofs", features = ["tests"] }

[build-dependencies]
cxx-build = "1.0"