change-id = 102579

[llvm]

download-ci-llvm = false

[build]

target = [ "x86_64-unknown-linux-gnu", "TARGET"]

cargo = "/home/user/.guix-profile/bin/cargo"
rustc = "/home/user/.guix-profile/bin/rustc"

optimized-compiler-builtins = false

docs = false

submodules = false
vendor = true

[install]

prefix = "PREFIX"

[rust]

debug = false
channel = "stable"

[target.x86_64-unknown-linux-gnu]

cc = "/home/user/.guix-profile/bin/gcc"
cxx = "/home/user/.guix-profile/bin/g++"
ar = "/home/user/.guix-profile/bin/ar"
linker = "/home/user/.guix-profile/bin/gcc"

llvm-config = "/home/user/.guix-profile/bin/llvm-config"

[target.TARGET]

llvm-config = "/home/user/.guix-profile/bin/llvm-config"

[dist]
