[package]
name = "fcmp_pp_rust"
version = "0.0.0"
edition = "2021"

[lib]
name = "fcmp_pp_rust"
crate-type = ["staticlib"]

[dependencies]

# TODO: replace j-berman with kayabaNerve once one of https://github.com/kayabaNerve/fcmp-plus-plus/pull/21
# or https://github.com/kayabaNerve/fcmp-plus-plus/pull/24 is merged

std-shims = { git = "https://github.com/j-berman/fcmp-plus-plus" }
rand_core = { version = "0.6", default-features = false }

helioselene = { git = "https://github.com/j-berman/fcmp-plus-plus" }
dalek-ff-group = { git = "https://github.com/j-berman/fcmp-plus-plus" }
ciphersuite = { git = "https://github.com/j-berman/fcmp-plus-plus", features = ["ed25519", "helioselene"] }

generalized-bulletproofs = { git = "https://github.com/j-berman/fcmp-plus-plus", features = ["tests"] }

ec-divisors = { git = "https://github.com/j-berman/fcmp-plus-plus", features = ["ed25519"] }
full-chain-membership-proofs = { git = "https://github.com/j-berman/fcmp-plus-plus" }

monero-fcmp-plus-plus = { git = "https://github.com/j-berman/fcmp-plus-plus" }

monero-generators = { git = "https://github.com/j-berman/fcmp-plus-plus" }

multiexp = { git = "https://github.com/j-berman/fcmp-plus-plus" }

[patch.crates-io]
crypto-bigint = { git = "https://github.com/kayabaNerve/crypto-bigint", branch = "c-repr" }

[profile.dev]
lto = "off"
panic = "abort"

[profile.release]
lto = "off"
panic = "abort"
