# Generated by Boost 1.84.0

if(TARGET Boost::headers)
  return()
endif()

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_headers ${boost_headers_VERSION} at ${boost_headers_DIR}")
endif()

mark_as_advanced(boost_headers_DIR)

# Compute the include and library directories relative to this file.

get_filename_component(_BOOST_CMAKEDIR "${CMAKE_CURRENT_LIST_DIR}/../" REALPATH)

# If the computed and the original directories are symlink-equivalent, use original
if(EXISTS "/monero/contrib/depends/work/staging/riscv64-linux-gnu/boost/1.84.0-b2625929280/monero/contrib/depends/riscv64-linux-gnu/lib/cmake")
  get_filename_component(_BOOST_CMAKEDIR_ORIGINAL "/monero/contrib/depends/work/staging/riscv64-linux-gnu/boost/1.84.0-b2625929280/monero/contrib/depends/riscv64-linux-gnu/lib/cmake" REALPATH)
  if(_BOOST_CMAKEDIR STREQUAL _BOOST_CMAKEDIR_ORIGINAL)
    set(_BOOST_CMAKEDIR "/monero/contrib/depends/work/staging/riscv64-linux-gnu/boost/1.84.0-b2625929280/monero/contrib/depends/riscv64-linux-gnu/lib/cmake")
  endif()
  unset(_BOOST_CMAKEDIR_ORIGINAL)
endif()

get_filename_component(_BOOST_INCLUDEDIR "${_BOOST_CMAKEDIR}/../../include/" ABSOLUTE)

add_library(Boost::headers INTERFACE IMPORTED)

set_target_properties(Boost::headers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_BOOST_INCLUDEDIR}"
)

unset(_BOOST_INCLUDEDIR)
unset(_BOOST_CMAKEDIR)
