[llvm]

download-ci-llvm = false

[build]

target = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

cargo = "/home/user/.guix-profile/bin/cargo"

rustc = "/home/user/.guix-profile/bin/rustc"

[install]

[rust]

[target.x86_64-unknown-linux-gnu]

cc = "/home/user/.guix-profile/bin/gcc"

cxx = "/home/user/.guix-profile/bin/g++"

ar = "/home/user/.guix-profile/bin/ar"

linker = "/home/user/.guix-profile/bin/gcc"

llvm-config = "/home/user/.guix-profile/bin/llvm-config"

[target.aarch64-unknown-linux-gnu]

llvm-config = "/home/user/.guix-profile/bin/llvm-config"
[dist]
