name: ci/gh-actions/depends

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/README.md'

env:
  APT_SET_CONF: |
        echo "Acquire::Retries \"3\";"         | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";"  | sudo tee -a /etc/apt/apt.conf.d/80-custom
  CCACHE_SETTINGS: |
        ccache --max-size=150M
        ccache --set-config=compression=true
  USE_DEVICE_TREZOR_MANDATORY: ON

jobs:
  build-cross:
    runs-on: ubuntu-20.04
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - name: "RISCV 64bit"
            host: "riscv64-linux-gnu"
            packages: "g++-riscv64-linux-gnu"
            rust_host: "riscv64gc-unknown-linux-gnu"
          - name: "ARM v7"
            host: "arm-linux-gnueabihf"
            packages: "g++-arm-linux-gnueabihf"
            rust_host: "armv7-unknown-linux-gnueabihf"
          - name: "ARM v8"
            host: "aarch64-linux-gnu"
            packages: "g++-aarch64-linux-gnu"
            rust_host: "aarch64-unknown-linux-gnu"
          - name: "i686 Linux"
            host: "i686-pc-linux-gnu"
            packages: "g++-multilib"
            rust_host: "i686-unknown-linux-gnu"
          - name: "Win64"
            host: "x86_64-w64-mingw32"
            packages: "g++-mingw-w64-x86-64"
            rust_host: "x86_64-pc-windows-gnu"
          - name: "x86_64 Linux"
            host: "x86_64-unknown-linux-gnu"
            rust_host: "x86_64-unknown-linux-gnu"
          - name: "Cross-Mac x86_64"
            host: "x86_64-apple-darwin"
            rust_host: "x86_64-apple-darwin"
          - name: "Cross-Mac aarch64"
            host: "aarch64-apple-darwin"
            rust_host: "aarch64-apple-darwin"
          - name: "x86_64 Freebsd"
            host: "x86_64-unknown-freebsd"
            packages: "clang-8"
            rust_host: "x86_64-unknown-freebsd"
          - name: "ARMv7 Android"
            host: "arm-linux-android"
            rust_host: "armv7-linux-androideabi"
          - name: "ARMv8 Android"
            host: "aarch64-linux-android"
            rust_host: "aarch64-linux-android"
    name: ${{ matrix.toolchain.name }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
# Most volatile cache
    - name: ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ matrix.toolchain.host }}-${{ github.sha }}
        restore-keys: ccache-${{ matrix.toolchain.host }}-
# Less volatile cache
    - name: depends cache
      uses: actions/cache@v4
      with:
        path: contrib/depends/built
        key: depends-${{ matrix.toolchain.host }}-${{ hashFiles('contrib/depends/packages/*') }}
        restore-keys: |
          depends-${{ matrix.toolchain.host }}-${{ hashFiles('contrib/depends/packages/*') }}
          depends-${{ matrix.toolchain.host }}-
    - uses: ./.github/actions/set-make-job-count
    - name: set apt conf
      run: ${{env.APT_SET_CONF}}
    - name: install dependencies
      run: sudo apt update; sudo apt -y install build-essential libtool cmake autotools-dev automake pkg-config python3 gperf bsdmainutils curl git ca-certificates ccache ${{ matrix.toolchain.packages }}
    - name: install rust target
      # We can't use the latest Rust due to LLVM 17 not working with old `ld`s (such as in Ubuntu 20.04) for RISC-V
      # We could update ld (a pain), update Ubuntu (requires a large amount of changes), or downgrade Rust
      # We can't use Rust 1.70 due to LLVM 16 requiring ld >= 2.40 when building for Windows
      run: rustup toolchain install 1.69; rustup default 1.69; rustup target add ${{ matrix.toolchain.rust_host }}
    - name: prepare w64-mingw32
      if: ${{ matrix.toolchain.host == 'x86_64-w64-mingw32' }}
      run: |
        sudo update-alternatives --set ${{ matrix.toolchain.host }}-g++ $(which ${{ matrix.toolchain.host }}-g++-posix)
        sudo update-alternatives --set ${{ matrix.toolchain.host }}-gcc $(which ${{ matrix.toolchain.host }}-gcc-posix)
    - name: build
      run: |
        ${{env.CCACHE_SETTINGS}}
        make depends target=${{ matrix.toolchain.host }} -j${{env.MAKE_JOB_COUNT}}
    - uses: actions/upload-artifact@v4
      if: ${{ matrix.toolchain.host == 'x86_64-w64-mingw32' || matrix.toolchain.host == 'x86_64-apple-darwin' || matrix.toolchain.host == 'aarch64-apple-darwin' || matrix.toolchain.host == 'x86_64-unknown-linux-gnu' }}
      with:
        name: ${{ matrix.toolchain.name }}
        path: |
          /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/${{ matrix.toolchain.host }}/release/bin/monero-wallet-cli*
          /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/${{ matrix.toolchain.host }}/release/bin/monerod*
